#include "legendre_hw.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>

static int ensure_directory(const char *path) {
    if (mkdir(path, 0755) == 0 || errno == EEXIST) {
        return 0;
    }
    return -1;
}

int main(void) {
    const int lmax = 50;
    const int L = 100;
    const double xs[] = {0.1, 0.5, 0.9, 0.99};
    const int nx = (int)(sizeof(xs) / sizeof(xs[0]));

    double Pf[lmax + 1];
    double Pb[lmax + 1];

    if (ensure_directory("results") != 0) {
        perror("results");
        return EXIT_FAILURE;
    }

    FILE *csv = fopen("results/double_values.csv", "w");
    if (csv == NULL) {
        perror("results/double_values.csv");
        return EXIT_FAILURE;
    }

    FILE *params = fopen("results/run_parameters.txt", "w");
    if (params == NULL) {
        perror("results/run_parameters.txt");
        fclose(csv);
        return EXIT_FAILURE;
    }

    fprintf(csv, "x,l,P_forward,P_backward\n");
    fprintf(params, "Legendre polynomial stability homework\n");
    fprintf(params, "double-precision C methods: forward recurrence and backward recurrence\n");
    fprintf(params, "high-precision reference and errors are generated by scripts/add_mpmath_reference_and_errors.py\n");
    fprintf(params, "lmax = %d\n", lmax);
    fprintf(params, "backward start L = %d\n", L);
    fprintf(params, "x values = 0.1, 0.5, 0.9, 0.99\n");

    for (int ix = 0; ix < nx; ++ix) {
        const double x = xs[ix];
        legendre_forward(x, lmax, Pf);
        legendre_backward(x, lmax, L, Pb);

        for (int ell = 0; ell <= lmax; ++ell) {
            fprintf(csv, "%.2f,%d,%.17e,%.17e\n", x, ell, Pf[ell], Pb[ell]);
        }
    }

    fclose(csv);
    fclose(params);
    return EXIT_SUCCESS;
}
